platform :ios, '11'
use_modular_headers!

target 'EthereumKitExample' do
  pod 'EthereumKit.swift', :path => '../'
  pod 'Erc20Kit.swift', :path => '../'
  pod 'UniswapKit.swift', :path => '../'
  pod 'HsToolKit.swift', git: 'https://github.com/horizontalsystems/hs-tool-kit-ios'

  pod 'SnapKit'
end

def testPods
  pod 'Cuckoo'
  pod 'Quick'
  pod 'Nimble'
end

target 'EthereumKitTests' do
  pod 'EthereumKit.swift', :path => '../'
  testPods
end
